const db ={

"Class 1 List of NCERT Text Books" :{
"book" :["Rimjhim Bhag I "],
"book2" :["Marigold Book I"],
"book3" :["	Math Magic Book I "],
"book4" :["	Ganit Ka Jadu Pustak I"],
"book5" :["	Rain Drops Book I (Special Series )"],
},

"Class 2 List of NCERT Text Books": {
"book6" :["•	Rimjhim II "],
"book7" :["•	Mari Gold II "],
"book8" :["•	Math Magic II "],
"book9" :["•	Ganit Ka Jadu II"],
"book10" :["•	Rain Drops Book II (Special Series ) "],


},

"Class 3 List of NCERT Text Books":{
"book12" :["•	Rimjhim Bhag III "],
"book13" :["•	Marigold Book III "],
"book14" :["•	Math Magic Book III "],
"book15" :["•	Ganit Ka Jadu Pustak III"],
"book16" :["•	Looking Around Book I "],
"book17" :["•	Aaspass Pustak I "],

},

"Class 4 List of NCERT Text Books": {
"book18" :["•	Rimjhim IV "],
"book19" :["•	Marigold IV "],
"book20" :["•	Math- Magic IV"],
"book21" :["•	Ganit Ka Jadu IV"],
"book22" :["•	Looking Around "],
"book23" :["•	Aaspass – EVS (Hindi)"],

},

"Class 5 List of NCERT Text Books": {
"book24" :["•	Rimjhim V (Hindi) "],
"book25" :["•	Marigold V (English)"],
"book26" :["•	Mathematics"],
"book27" :["•	Ganit "],
"book28" :["•	Looking Around"],
"book29" :["•	Aaspass "],

},

"Class 6 List of NCERT Text Books": {
"book30" :["•	Vasant Bhag I"],
"book31" :["•	Bal Ramkatha "],
"book32" :["•	Durva (Second Lng.)"],  
"book33" :["•	Honey Suckle "],
"book34" :["•	A Pact with the Sun"],
"book35" :["•	Ruchira – Prathamo Bhag"],
"book36" :["•	Mathematics "],
"book37" :["•	Ganit "],
"book38" :["•	Science "],
"book39" :["•	Vigyan "],
"book40" :["•	Our past – History"],
"book41" :["•	Hamara Atit – Itihas"],
"book42" :["•	The Earth Our Habitate – Geogrophy"],
"book43" :["•	Prithvi Hamara Abhas – Bhugol "],
"book44" :["•	Social and Political Life "],
"book45" :["•	Samajik Aur Rajniti Jeevan "],

},

"Class 7 List of NCERT Text Books": {
"book46" :["•	Vasant II "],
"book48" :["•	Bal Mahabharat Katha"],
"book49" :["•	Durva – Second Lng. II"],
"book50" :["•	Honey Comb – English "],
"book51" :["•	 Alien Hand – Suppl.Eng"],
"book52" :["•	Ruchira II – Sanskrit "],
"book53" :["•	Mathematics "],
"book54" :["•	Ganit "],
"book56" :["•	Science"],
"book57" :["•	Vigyan -"],
"book58" :["•	Our Past II – History"],
"book59" :["•	Hamara Atiti II – Itihas"],
"book60" :["•	Our Environment – Geogrophy"],
"book61" :["•	Hamara Paryavaran – Bhugol "],
"book62" :["•	Social and Political Life II "],
"book63" :["•	Samajik Aur Rajniti Jeevan II "],

},

"Class 8 List of NCERT Text Books": {
"book64" :["•	Vasant – Hindi "],
"book65" :["•	Bharat Ki Khoj – Suppl. Hindi"],
"book66" :["•	Durva – Second Lng. Hindi "],
"book67" :["•	Honey Dew – English  "],
"book68" :["•	It So Happened – Suppl. English"],
"book69" :["•	Ruchira III – Sanskrit "],
"book70" :["•	Mathematics "],
"book71" :["•	Ganit "],
"book72" :["•	Science "],
"book73" :["•	Vigyan "],
"book74" :["•	Our Past III part I – History"],
"book75" :["•	Hamare Aatit III Bhag I – Itihas"],
"book76" :["•	Our Past III part II – History "],
"book77" :["•	Hamare Aatit III Bhag II – Itihas"],
"book78" :["•	Resourse & Development – Geogrophy "],
"book79" :["•	Bhugol "],
"book80" :["•	Social & Political Life  "],
"book81" :["•	Samajik Aur Rajniti Jeevan "],

},

"Class 9 List of NCERT Text Books" :{
"book82" :["•	Kshitij  "],
"book83" :["•	Kritika – Hindi Suppl"],
"book84" :["•	Sparsh – 2nd Lang. Hindi"],
"book85" :["•	Sanchayan Suppl. Hindi ( 2nd Lang.)"],
"book86" :["•	Beehive – English Text "],
"book87" :["•	Moments – English Suppl. Rdr"],
"book88" :["•	Shemusi – Sanskrit "],
"book89" :["•	Mathematics "],
"book90" :["•	Ganit "],
"book91" :["•	Science "],
"book92" :["•	Vigyan "],
"book93" :["•	India & Comtemprary World – History "],
"book94" :["•	Bharat Aur Samakalin Vishwa – Itihas "],
"book95" :["•	Contemprary India – Geogrophy "],
"book96" :["•	Samakalin Bharat – Bhugol "],
"book97" :["•	Economics "],
"book98" :["•	Arthshastra "],
"book99" :["•	Democretic Politics"],
"book100" :["•	Lokta0ik Rajniti "],

},

"Class 10 List of NCERT Text Books": {
"book101" :["•	Khitij – Hindi "],
"book102" :["•	Kritika – Hindi Suppl "],
"book103" :["•	Sparsh -2nd Lang. Hindi "],
"book104" :["•	Sanchayan – Suppl. Hindi ( 2nd Lang.) "],
"book105" :["•	First Flight – English Text "],
"book106" :["•	Footprints without Feet – English Suppl. Rdr "],
"book107" :["•	Shemusi II – Sanskrit  "],
"book108" :["•	Mathematics "],
"book109" :["•	Ganit "],
"book110" :["•	Science "],
"book111" :["•	Vigyan "],
"book112" :["•	India & Contemporary World II – History "],
"book113" :["•	Bharat Aur Samakalin Vishwa II – Itihas "],
"book114" :["•	Contempropry India – Geogrophy "],
"book115" :["•	Samakalin Bharat – Bhugol "],
"book116" :["•	Understanding Economic Development – Economic"],
"book117" :["•	Arthik Vikas Ki Samajh – Arthashastra "],
"book118" :["•	Democratic Politics II  "],
"book119" :["•	Loktaik Rajniti II "],

},

"Class 11 List of NCERT Text Books":{
"book120" :["•	Aroh – Hindi Core "],
"book121" :["•	Vitan – Suppl.Hindi I ( Core ) "],
"book122" :["•	Antara – Hindi Lit. "],
"book123" :["•	Antaral – Suppl. Hindi Lit. I"],
"book124" :["•	Abhvyakti Aur Madhyam(Core & Lit Cl XI & XII)"],
"book125" :["•	Hornbill – English Core "],
"book126" :["•	Snapshot – Suppl. Eng Core"],
"book127" :["•	Owoen words – English Lit. "],
"book128" :["•	Sanskrit – Bhaswati "],
"book129" :["•	Sanskrit – Shaswati "],
"book130" :["•	Mathematics "],
"book131" :["•	Ganit "],
"book132" :["•	Biology "],
"book133" :["•	Jeev Vigyan"],
"book134" :["•	Chemistry Part I"],
"book135" :["•	Chemistry Part II"],
"book136" :["•	Rasayan Vigyan Bhag I "],
"book137" :["•	Rasayan Vigyan Bhag II "],
"book138" :["•	Physics Part I "],
"book139" :["•	Physics Part II "],
"book140" :["•	Bhautik Bhag I "],
"book141" :["•	Bhautik Bhag II "],
"book142" :["•	Themes of World History"],
"book143" :["•	Vishva Itihas Ke Kuch Vishay"],
"book144" :["•	Fundamental of Physical Geo. "],
"book145" :["•	Bhautuk Bhugol Ke Mool Sidhant "],
"book146" :["•	India Phy. Environment "],
"book147" :["•	Bharat Bhautik Paryavaran"],
"book148" :["•	Prac.Work In Geogrophy "],
"book149" :["•	Bhugol Mein Prayogatmak Karya "],
"book150" :["•	Eco. Statistics "],
"book151" :["•	Arthashastra Mein Sankhiki"],
"book152" :["•	Indian Eco. Development "],
"book153" :["•	Bharatiya Arthvyavasta Ka Vikas"],
"book154" :["•	Indian Constitution at Work "],
"book155" :["•	Bharatiya sanvidhan Ka Karya "],
"book156" :["•	Pol. Theory part II "],
"book157" :["•	Rajniti – Siddhant Bhag II"],
"book158" :["•	Sociology Part I "],
"book159" :["•	Samajshastra Bhag I "],
"book160" :["•	Understanding Society Part II"],
"book161" :["•	Samaj Ka Bodh Bhag II"],
"book162" :["•	Business Studies "],
"book163" :["•	Vyavasaik Adhyayan "],
"book164" :["•	Accts Part I "],
"book165" :["•	Lekhashatra Bhag I"],
"book166" :["•	Accts Part II "],
"book167" :["•	Lekhashatra Bhag II"],
"book168" :["•	Psychology "],
"book169" :["•	Manovigyan Ka Parichaya "],
"book170" :["•	Computers & Communication Technology Part I "],
"book171" :["•	Srijan I (Textbook in Creative Writing & Translation"],  
"book172" :["•	Living Craft Tradition of India (Textbook in Heritage "],
"book173" :["•	The Story of Graphic Design  "],
"book174" :["•	Human Ecology & Family Science Part I"],
"book175" :["•	Human Ecology & Family Science Part II "],
"book176" :["•	Bharatiya Hastakala Ki Paramparayen "],
"book177" :["•	Computers & Communication Technology Part II "],
"book178" :["•	Exploring the Craft Tradition of India  "],
"book179" :["•	Graphic Design Ek Kahani Class XI  "],
"book180" :["•	Bharatiya Hastakala Paramparaon Ki Khoj"],
"book181" :["•	Computer Aur Sanchar Pradyogiki Bhag I "],
"book182" :["•	An Introduction to Indian Art"],
"book183" :["•	Computer Aur Sanchar Pradyogiki Bhag II"],

},

"Class 12 List of NCERT Text Books" :{
"book184" :["•	Aaroh – Hindi Core "],
"book185" :["•	Vitan – Suppl.Hindi I ( Core ) "],
"book186" :["•	Antara – Hindi Lit. "],
"book187" :["•	Antaral – Suppl. Hindi Lit. I "],
"book188" :["•	Flemingo – English Core "],
"book189" :["•	Vistas – Suppl. Eng Core "],
"book190" :["•	Keladaiscope – English Lit. "],
"book191" :["•	Sanskrit – Bhaswati II "],
"book192" :["•	Sanskrit – Shaswati II "],
"book193" :["•	Mathematics Part I "],
"book194" :["•	Mathematics Part II "],
"book195" :["•	Ganit Bhag I "],
"book196" :["•	Ganit Bhag II "],
"book197" :["•	Biology "],
"book198" :["•	Jeev Vigyan "],
"book199" :["•	Chemistry I "],
"book200" :["•	Chemistry II "],
"book201" :["•	Rasayan Vigyan Bhag I "],
"book202" :["•	Rasayan Vigyan Bhag II "],
"book203" :["•	Physics I "],
"book204" :["•	Physics II "],
"book205" :["•	Bhautik I "],
"book206" :["•	Bhautik II "],
"book207" :["•	Thymes In Indian History Part I "],
"book208" :["•	Thymes In Indian History Part II "],
"book209" :["•	Thymes In Indian History Part III "],
"book210" :["•	Bharatiya Itihas Ke Kuch Ansh Bhag I "],
"book211" :["•	Bharatiya Itihas Ke Kuch Ansh Bhag II "],
"book212" :["•	Bharatiya Itihas Ke Kuch Ansh Bhag III " ] ,
"book213" :["•	Fundamentals of Human Geogrophy "],
"book214" :["•	Manav Bhugol Ke Mul Sidhant " ] ,
"book215" :["•	India People and Economy " ] ,
"book216" :["•	Bharat – Log Aur Arthavyavastha " ] ,
"book217" :["•	Prac.Work In Geogrophy " ] ,
"book218" :["•	Bhugol Mein Prayogatmak Karya " ] ,
"book219" :["•	Microeconomics "],
"book220" :["•	Vyasthi Arthashastra  " ] ,
"book221" :["•	Macroeconomics " ] ,
"book222" :["•	Samashti Arthashastra "],
"book223" :["•	Contemporary World Politics  "],
"book224" :["•	Samakalin Vishwa Rajniti "],
"book225" :["•	Social Change in India "],
"book226" :["•	Bharat Mein Samajik Parivartan "],
"book227" :["•	Indian Society – Sociology "],
"book228" :["•	Bharatiya Samaj – Samajshastra "],
"book229" :["•	Business Studies I "],
"book230" :["•	Business Studies II "],
"book231" :["•	Vyavasaik Adhyayan I "],
"book232" :["•	Vyavasaik Adhyayan II"],
"book233" :["•	Accountancy I "],
"book234" :["•	Accountancy II"],
"book235" :["•	Accountancy III"],
"book236" :["•	Politics in India since Independence  "],
"book237" :["•	Lekhashatra I  "],
"book238" :["•	Lekhashastra II"],
"book239" :["•	Swata0a Bharat Mein Rajniti"],
"book240" :["•	Psychology "],
"book241" :["•	Manovigyan Ka Parichaya"],
"book242" :["•	Craft Tradition of India (Textbook in Heritage Craft "],
"book243" :["•	Towards a New Age of Graphic Design Class XII "],
"book244" :["•	List of Textbooks (Urdu) "],

},

}